# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alignmentGuide.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='alignmentGuide.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x61lignmentGuide.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\"\xe4\x01\n\x0e\x41lignmentGuide\x12\x1b\n\x04uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12\x41\n\x0borientation\x18\x02 \x01(\x0e\x32,.rv.data.AlignmentGuide.GuidelineOrientation\x12\x10\n\x08location\x18\x03 \x01(\x01\"`\n\x14GuidelineOrientation\x12$\n GUIDELINE_ORIENTATION_HORIZONTAL\x10\x00\x12\"\n\x1eGUIDELINE_ORIENTATION_VERTICAL\x10\x01\x62\x06proto3'
  ,
  dependencies=[basicTypes__pb2.DESCRIPTOR,])



_ALIGNMENTGUIDE_GUIDELINEORIENTATION = _descriptor.EnumDescriptor(
  name='GuidelineOrientation',
  full_name='rv.data.AlignmentGuide.GuidelineOrientation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GUIDELINE_ORIENTATION_HORIZONTAL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GUIDELINE_ORIENTATION_VERTICAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=184,
  serialized_end=280,
)
_sym_db.RegisterEnumDescriptor(_ALIGNMENTGUIDE_GUIDELINEORIENTATION)


_ALIGNMENTGUIDE = _descriptor.Descriptor(
  name='AlignmentGuide',
  full_name='rv.data.AlignmentGuide',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='rv.data.AlignmentGuide.uuid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='rv.data.AlignmentGuide.orientation', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location', full_name='rv.data.AlignmentGuide.location', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ALIGNMENTGUIDE_GUIDELINEORIENTATION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=280,
)

_ALIGNMENTGUIDE.fields_by_name['uuid'].message_type = basicTypes__pb2._UUID
_ALIGNMENTGUIDE.fields_by_name['orientation'].enum_type = _ALIGNMENTGUIDE_GUIDELINEORIENTATION
_ALIGNMENTGUIDE_GUIDELINEORIENTATION.containing_type = _ALIGNMENTGUIDE
DESCRIPTOR.message_types_by_name['AlignmentGuide'] = _ALIGNMENTGUIDE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AlignmentGuide = _reflection.GeneratedProtocolMessageType('AlignmentGuide', (_message.Message,), {
  'DESCRIPTOR' : _ALIGNMENTGUIDE,
  '__module__' : 'alignmentGuide_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.AlignmentGuide)
  })
_sym_db.RegisterMessage(AlignmentGuide)


# @@protoc_insertion_point(module_scope)
