# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: background.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import graphicsData_pb2 as graphicsData__pb2
import basicTypes_pb2 as basicTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='background.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x62\x61\x63kground.proto\x12\x07rv.data\x1a\x12graphicsData.proto\x1a\x10\x62\x61sicTypes.proto\"y\n\nBackground\x12\x12\n\nis_enabled\x18\x03 \x01(\x08\x12\x1f\n\x05\x63olor\x18\x01 \x01(\x0b\x32\x0e.rv.data.ColorH\x00\x12.\n\x08gradient\x18\x02 \x01(\x0b\x32\x1a.rv.data.Graphics.GradientH\x00\x42\x06\n\x04\x46illb\x06proto3'
  ,
  dependencies=[graphicsData__pb2.DESCRIPTOR,basicTypes__pb2.DESCRIPTOR,])




_BACKGROUND = _descriptor.Descriptor(
  name='Background',
  full_name='rv.data.Background',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_enabled', full_name='rv.data.Background.is_enabled', index=0,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='rv.data.Background.color', index=1,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gradient', full_name='rv.data.Background.gradient', index=2,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Fill', full_name='rv.data.Background.Fill',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=67,
  serialized_end=188,
)

_BACKGROUND.fields_by_name['color'].message_type = basicTypes__pb2._COLOR
_BACKGROUND.fields_by_name['gradient'].message_type = graphicsData__pb2._GRAPHICS_GRADIENT
_BACKGROUND.oneofs_by_name['Fill'].fields.append(
  _BACKGROUND.fields_by_name['color'])
_BACKGROUND.fields_by_name['color'].containing_oneof = _BACKGROUND.oneofs_by_name['Fill']
_BACKGROUND.oneofs_by_name['Fill'].fields.append(
  _BACKGROUND.fields_by_name['gradient'])
_BACKGROUND.fields_by_name['gradient'].containing_oneof = _BACKGROUND.oneofs_by_name['Fill']
DESCRIPTOR.message_types_by_name['Background'] = _BACKGROUND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Background = _reflection.GeneratedProtocolMessageType('Background', (_message.Message,), {
  'DESCRIPTOR' : _BACKGROUND,
  '__module__' : 'background_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.Background)
  })
_sym_db.RegisterMessage(Background)


# @@protoc_insertion_point(module_scope)
