# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: digitalAudio.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='digitalAudio.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x64igitalAudio.proto\x12\x07rv.data\"\xb5\x08\n\x0c\x44igitalAudio\x1a\xb4\x02\n\x05Setup\x12(\n\x05\x62uses\x18\x01 \x03(\x0b\x32\x19.rv.data.DigitalAudio.Bus\x12\x34\n\x0emonitor_device\x18\x02 \x01(\x0b\x32\x1c.rv.data.DigitalAudio.Device\x12\x38\n\x12main_output_device\x18\x03 \x01(\x0b\x32\x1c.rv.data.DigitalAudio.Device\x12\x1d\n\x15\x65nable_sdi_ndi_device\x18\x04 \x01(\x08\x12\x34\n\x0esdi_ndi_device\x18\x05 \x01(\x0b\x32\x1c.rv.data.DigitalAudio.Device\x12\x18\n\x10monitor_on_mains\x18\x06 \x01(\x08\x12\"\n\x1a\x64isable_main_output_device\x18\x07 \x01(\x08\x1aY\n\x03\x42us\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05muted\x18\x02 \x01(\x08\x12\x0c\n\x04solo\x18\x03 \x01(\x08\x12\x11\n\ttest_tone\x18\x04 \x01(\x08\x12\x14\n\x0cmaster_level\x18\x05 \x01(\x01\x1a\x92\x05\n\x06\x44\x65vice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08renderID\x18\x02 \x01(\t\x12\x34\n\x07\x66ormats\x18\x03 \x03(\x0b\x32#.rv.data.DigitalAudio.Device.Format\x12\x35\n\x07routing\x18\x04 \x01(\x0b\x32$.rv.data.DigitalAudio.Device.Routing\x1a\x8e\x01\n\x06\x46ormat\x12\x13\n\x0bsample_rate\x18\x01 \x01(\r\x12\x11\n\tbit_depth\x18\x02 \x01(\r\x12\x36\n\x04type\x18\x03 \x01(\x0e\x32(.rv.data.DigitalAudio.Device.Format.Type\"$\n\x04Type\x12\x0c\n\x08TYPE_INT\x10\x00\x12\x0e\n\nTYPE_FLOAT\x10\x01\x1a\x34\n\x03Map\x12\x15\n\rchannel_index\x18\x01 \x01(\r\x12\x16\n\x0emapped_indices\x18\x02 \x03(\r\x1al\n\x07\x43hannel\x12\x13\n\x0bmute_enable\x18\x01 \x01(\x08\x12\x13\n\x0bsolo_enable\x18\x02 \x01(\x08\x12\x13\n\x0btone_enable\x18\x03 \x01(\x08\x12\x13\n\x0b\x61udio_delay\x18\x04 \x01(\x01\x12\r\n\x05level\x18\x05 \x01(\x01\x1a\xc5\x01\n\x07Routing\x12\x36\n\x08\x63hannels\x18\x01 \x03(\x0b\x32$.rv.data.DigitalAudio.Device.Channel\x12-\n\x03map\x18\x02 \x03(\x0b\x32 .rv.data.DigitalAudio.Device.Map\x12\x15\n\ris_custom_map\x18\x03 \x01(\x08\x12<\n\x0emaster_channel\x18\x04 \x01(\x0b\x32$.rv.data.DigitalAudio.Device.Channelb\x06proto3'
)



_DIGITALAUDIO_DEVICE_FORMAT_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='rv.data.DigitalAudio.Device.Format.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_INT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TYPE_FLOAT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=709,
  serialized_end=745,
)
_sym_db.RegisterEnumDescriptor(_DIGITALAUDIO_DEVICE_FORMAT_TYPE)


_DIGITALAUDIO_SETUP = _descriptor.Descriptor(
  name='Setup',
  full_name='rv.data.DigitalAudio.Setup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='buses', full_name='rv.data.DigitalAudio.Setup.buses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='monitor_device', full_name='rv.data.DigitalAudio.Setup.monitor_device', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='main_output_device', full_name='rv.data.DigitalAudio.Setup.main_output_device', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable_sdi_ndi_device', full_name='rv.data.DigitalAudio.Setup.enable_sdi_ndi_device', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sdi_ndi_device', full_name='rv.data.DigitalAudio.Setup.sdi_ndi_device', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='monitor_on_mains', full_name='rv.data.DigitalAudio.Setup.monitor_on_mains', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='disable_main_output_device', full_name='rv.data.DigitalAudio.Setup.disable_main_output_device', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=357,
)

_DIGITALAUDIO_BUS = _descriptor.Descriptor(
  name='Bus',
  full_name='rv.data.DigitalAudio.Bus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rv.data.DigitalAudio.Bus.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='muted', full_name='rv.data.DigitalAudio.Bus.muted', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='solo', full_name='rv.data.DigitalAudio.Bus.solo', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_tone', full_name='rv.data.DigitalAudio.Bus.test_tone', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='master_level', full_name='rv.data.DigitalAudio.Bus.master_level', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=448,
)

_DIGITALAUDIO_DEVICE_FORMAT = _descriptor.Descriptor(
  name='Format',
  full_name='rv.data.DigitalAudio.Device.Format',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sample_rate', full_name='rv.data.DigitalAudio.Device.Format.sample_rate', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bit_depth', full_name='rv.data.DigitalAudio.Device.Format.bit_depth', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='rv.data.DigitalAudio.Device.Format.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DIGITALAUDIO_DEVICE_FORMAT_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=603,
  serialized_end=745,
)

_DIGITALAUDIO_DEVICE_MAP = _descriptor.Descriptor(
  name='Map',
  full_name='rv.data.DigitalAudio.Device.Map',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_index', full_name='rv.data.DigitalAudio.Device.Map.channel_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mapped_indices', full_name='rv.data.DigitalAudio.Device.Map.mapped_indices', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=747,
  serialized_end=799,
)

_DIGITALAUDIO_DEVICE_CHANNEL = _descriptor.Descriptor(
  name='Channel',
  full_name='rv.data.DigitalAudio.Device.Channel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mute_enable', full_name='rv.data.DigitalAudio.Device.Channel.mute_enable', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='solo_enable', full_name='rv.data.DigitalAudio.Device.Channel.solo_enable', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tone_enable', full_name='rv.data.DigitalAudio.Device.Channel.tone_enable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='audio_delay', full_name='rv.data.DigitalAudio.Device.Channel.audio_delay', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='rv.data.DigitalAudio.Device.Channel.level', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=801,
  serialized_end=909,
)

_DIGITALAUDIO_DEVICE_ROUTING = _descriptor.Descriptor(
  name='Routing',
  full_name='rv.data.DigitalAudio.Device.Routing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channels', full_name='rv.data.DigitalAudio.Device.Routing.channels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='map', full_name='rv.data.DigitalAudio.Device.Routing.map', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_custom_map', full_name='rv.data.DigitalAudio.Device.Routing.is_custom_map', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='master_channel', full_name='rv.data.DigitalAudio.Device.Routing.master_channel', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=912,
  serialized_end=1109,
)

_DIGITALAUDIO_DEVICE = _descriptor.Descriptor(
  name='Device',
  full_name='rv.data.DigitalAudio.Device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rv.data.DigitalAudio.Device.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='renderID', full_name='rv.data.DigitalAudio.Device.renderID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='formats', full_name='rv.data.DigitalAudio.Device.formats', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='routing', full_name='rv.data.DigitalAudio.Device.routing', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DIGITALAUDIO_DEVICE_FORMAT, _DIGITALAUDIO_DEVICE_MAP, _DIGITALAUDIO_DEVICE_CHANNEL, _DIGITALAUDIO_DEVICE_ROUTING, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=1109,
)

_DIGITALAUDIO = _descriptor.Descriptor(
  name='DigitalAudio',
  full_name='rv.data.DigitalAudio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_DIGITALAUDIO_SETUP, _DIGITALAUDIO_BUS, _DIGITALAUDIO_DEVICE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=1109,
)

_DIGITALAUDIO_SETUP.fields_by_name['buses'].message_type = _DIGITALAUDIO_BUS
_DIGITALAUDIO_SETUP.fields_by_name['monitor_device'].message_type = _DIGITALAUDIO_DEVICE
_DIGITALAUDIO_SETUP.fields_by_name['main_output_device'].message_type = _DIGITALAUDIO_DEVICE
_DIGITALAUDIO_SETUP.fields_by_name['sdi_ndi_device'].message_type = _DIGITALAUDIO_DEVICE
_DIGITALAUDIO_SETUP.containing_type = _DIGITALAUDIO
_DIGITALAUDIO_BUS.containing_type = _DIGITALAUDIO
_DIGITALAUDIO_DEVICE_FORMAT.fields_by_name['type'].enum_type = _DIGITALAUDIO_DEVICE_FORMAT_TYPE
_DIGITALAUDIO_DEVICE_FORMAT.containing_type = _DIGITALAUDIO_DEVICE
_DIGITALAUDIO_DEVICE_FORMAT_TYPE.containing_type = _DIGITALAUDIO_DEVICE_FORMAT
_DIGITALAUDIO_DEVICE_MAP.containing_type = _DIGITALAUDIO_DEVICE
_DIGITALAUDIO_DEVICE_CHANNEL.containing_type = _DIGITALAUDIO_DEVICE
_DIGITALAUDIO_DEVICE_ROUTING.fields_by_name['channels'].message_type = _DIGITALAUDIO_DEVICE_CHANNEL
_DIGITALAUDIO_DEVICE_ROUTING.fields_by_name['map'].message_type = _DIGITALAUDIO_DEVICE_MAP
_DIGITALAUDIO_DEVICE_ROUTING.fields_by_name['master_channel'].message_type = _DIGITALAUDIO_DEVICE_CHANNEL
_DIGITALAUDIO_DEVICE_ROUTING.containing_type = _DIGITALAUDIO_DEVICE
_DIGITALAUDIO_DEVICE.fields_by_name['formats'].message_type = _DIGITALAUDIO_DEVICE_FORMAT
_DIGITALAUDIO_DEVICE.fields_by_name['routing'].message_type = _DIGITALAUDIO_DEVICE_ROUTING
_DIGITALAUDIO_DEVICE.containing_type = _DIGITALAUDIO
DESCRIPTOR.message_types_by_name['DigitalAudio'] = _DIGITALAUDIO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DigitalAudio = _reflection.GeneratedProtocolMessageType('DigitalAudio', (_message.Message,), {

  'Setup' : _reflection.GeneratedProtocolMessageType('Setup', (_message.Message,), {
    'DESCRIPTOR' : _DIGITALAUDIO_SETUP,
    '__module__' : 'digitalAudio_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.DigitalAudio.Setup)
    })
  ,

  'Bus' : _reflection.GeneratedProtocolMessageType('Bus', (_message.Message,), {
    'DESCRIPTOR' : _DIGITALAUDIO_BUS,
    '__module__' : 'digitalAudio_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.DigitalAudio.Bus)
    })
  ,

  'Device' : _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), {

    'Format' : _reflection.GeneratedProtocolMessageType('Format', (_message.Message,), {
      'DESCRIPTOR' : _DIGITALAUDIO_DEVICE_FORMAT,
      '__module__' : 'digitalAudio_pb2'
      # @@protoc_insertion_point(class_scope:rv.data.DigitalAudio.Device.Format)
      })
    ,

    'Map' : _reflection.GeneratedProtocolMessageType('Map', (_message.Message,), {
      'DESCRIPTOR' : _DIGITALAUDIO_DEVICE_MAP,
      '__module__' : 'digitalAudio_pb2'
      # @@protoc_insertion_point(class_scope:rv.data.DigitalAudio.Device.Map)
      })
    ,

    'Channel' : _reflection.GeneratedProtocolMessageType('Channel', (_message.Message,), {
      'DESCRIPTOR' : _DIGITALAUDIO_DEVICE_CHANNEL,
      '__module__' : 'digitalAudio_pb2'
      # @@protoc_insertion_point(class_scope:rv.data.DigitalAudio.Device.Channel)
      })
    ,

    'Routing' : _reflection.GeneratedProtocolMessageType('Routing', (_message.Message,), {
      'DESCRIPTOR' : _DIGITALAUDIO_DEVICE_ROUTING,
      '__module__' : 'digitalAudio_pb2'
      # @@protoc_insertion_point(class_scope:rv.data.DigitalAudio.Device.Routing)
      })
    ,
    'DESCRIPTOR' : _DIGITALAUDIO_DEVICE,
    '__module__' : 'digitalAudio_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.DigitalAudio.Device)
    })
  ,
  'DESCRIPTOR' : _DIGITALAUDIO,
  '__module__' : 'digitalAudio_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.DigitalAudio)
  })
_sym_db.RegisterMessage(DigitalAudio)
_sym_db.RegisterMessage(DigitalAudio.Setup)
_sym_db.RegisterMessage(DigitalAudio.Bus)
_sym_db.RegisterMessage(DigitalAudio.Device)
_sym_db.RegisterMessage(DigitalAudio.Device.Format)
_sym_db.RegisterMessage(DigitalAudio.Device.Map)
_sym_db.RegisterMessage(DigitalAudio.Device.Channel)
_sym_db.RegisterMessage(DigitalAudio.Device.Routing)


# @@protoc_insertion_point(module_scope)
