# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: groups.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2
import hotKey_pb2 as hotKey__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='groups.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cgroups.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\x1a\x0chotKey.proto\"\xc7\x01\n\x05Group\x12\x1b\n\x04uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1d\n\x05\x63olor\x18\x03 \x01(\x0b\x32\x0e.rv.data.Color\x12\x1f\n\x06hotKey\x18\x04 \x01(\x0b\x32\x0f.rv.data.HotKey\x12\x33\n\x1c\x61pplication_group_identifier\x18\x05 \x01(\x0b\x32\r.rv.data.UUID\x12\x1e\n\x16\x61pplication_group_name\x18\x06 \x01(\t\"3\n\x11ProGroupsDocument\x12\x1e\n\x06groups\x18\x01 \x03(\x0b\x32\x0e.rv.data.Groupb\x06proto3'
  ,
  dependencies=[basicTypes__pb2.DESCRIPTOR,hotKey__pb2.DESCRIPTOR,])




_GROUP = _descriptor.Descriptor(
  name='Group',
  full_name='rv.data.Group',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='rv.data.Group.uuid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='rv.data.Group.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='rv.data.Group.color', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hotKey', full_name='rv.data.Group.hotKey', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='application_group_identifier', full_name='rv.data.Group.application_group_identifier', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='application_group_name', full_name='rv.data.Group.application_group_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=257,
)


_PROGROUPSDOCUMENT = _descriptor.Descriptor(
  name='ProGroupsDocument',
  full_name='rv.data.ProGroupsDocument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='groups', full_name='rv.data.ProGroupsDocument.groups', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=310,
)

_GROUP.fields_by_name['uuid'].message_type = basicTypes__pb2._UUID
_GROUP.fields_by_name['color'].message_type = basicTypes__pb2._COLOR
_GROUP.fields_by_name['hotKey'].message_type = hotKey__pb2._HOTKEY
_GROUP.fields_by_name['application_group_identifier'].message_type = basicTypes__pb2._UUID
_PROGROUPSDOCUMENT.fields_by_name['groups'].message_type = _GROUP
DESCRIPTOR.message_types_by_name['Group'] = _GROUP
DESCRIPTOR.message_types_by_name['ProGroupsDocument'] = _PROGROUPSDOCUMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Group = _reflection.GeneratedProtocolMessageType('Group', (_message.Message,), {
  'DESCRIPTOR' : _GROUP,
  '__module__' : 'groups_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.Group)
  })
_sym_db.RegisterMessage(Group)

ProGroupsDocument = _reflection.GeneratedProtocolMessageType('ProGroupsDocument', (_message.Message,), {
  'DESCRIPTOR' : _PROGROUPSDOCUMENT,
  '__module__' : 'groups_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.ProGroupsDocument)
  })
_sym_db.RegisterMessage(ProGroupsDocument)


# @@protoc_insertion_point(module_scope)
