# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: input.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2
import graphicsData_pb2 as graphicsData__pb2
import digitalAudio_pb2 as digitalAudio__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='input.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0binput.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\x1a\x12graphicsData.proto\x1a\x12\x64igitalAudio.proto\"\xa5\x04\n\nVideoInput\x12\x1b\n\x04uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12\x18\n\x10user_description\x18\x02 \x01(\t\x12\x36\n\x12video_input_device\x18\x03 \x01(\x0b\x32\x1a.rv.data.Media.VideoDevice\x12%\n\rdisplay_color\x18\x04 \x01(\x0b\x32\x0e.rv.data.Color\x12$\n\x0ethumbnail_path\x18\x05 \x01(\x0b\x32\x0c.rv.data.URL\x12\x37\n\naudio_type\x18\x08 \x01(\x0e\x32#.rv.data.VideoInput.AudioDeviceType\x12\x34\n\x0c\x61udio_device\x18\x06 \x01(\x0b\x32\x1c.rv.data.DigitalAudio.DeviceH\x00\x12\x32\n\x0cvideo_device\x18\x07 \x01(\x0b\x32\x1a.rv.data.Media.VideoDeviceH\x00\x1a\x37\n\x10SettingsDocument\x12#\n\x06inputs\x18\x01 \x03(\x0b\x32\x13.rv.data.VideoInput\"m\n\x0f\x41udioDeviceType\x12\x1d\n\x19\x41UDIO_DEVICE_TYPE_DEFAULT\x10\x00\x12\x1a\n\x16\x41UDIO_DEVICE_TYPE_NONE\x10\x01\x12\x1f\n\x1b\x41UDIO_DEVICE_TYPE_ALTERNATE\x10\x02\x42\x10\n\x0e\x41ltAudioSource\"\xaa\x04\n\nAudioInput\x12\x1b\n\x04uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12\x18\n\x10user_description\x18\x02 \x01(\t\x12\x37\n\rbehavior_mode\x18\x05 \x01(\x0b\x32 .rv.data.AudioInput.BehaviorMode\x12\x34\n\x0c\x61udio_device\x18\x03 \x01(\x0b\x32\x1c.rv.data.DigitalAudio.DeviceH\x00\x12\x32\n\x0cvideo_device\x18\x04 \x01(\x0b\x32\x1a.rv.data.Media.VideoDeviceH\x00\x1a\xb7\x02\n\x0c\x42\x65haviorMode\x12\x31\n\x02on\x18\x01 \x01(\x0b\x32#.rv.data.AudioInput.BehaviorMode.OnH\x00\x12\x33\n\x03off\x18\x02 \x01(\x0b\x32$.rv.data.AudioInput.BehaviorMode.OffH\x00\x12:\n\x07\x61uto_on\x18\x03 \x01(\x0b\x32\'.rv.data.AudioInput.BehaviorMode.AutoOnH\x00\x12<\n\x08\x61uto_off\x18\x04 \x01(\x0b\x32(.rv.data.AudioInput.BehaviorMode.AutoOffH\x00\x1a\x04\n\x02On\x1a\x05\n\x03Off\x1a\t\n\x07\x41utoOff\x1a%\n\x06\x41utoOn\x12\x1b\n\x13linked_video_inputs\x18\x01 \x03(\rB\x06\n\x04ModeB\x08\n\x06Sourceb\x06proto3'
  ,
  dependencies=[basicTypes__pb2.DESCRIPTOR,graphicsData__pb2.DESCRIPTOR,digitalAudio__pb2.DESCRIPTOR,])



_VIDEOINPUT_AUDIODEVICETYPE = _descriptor.EnumDescriptor(
  name='AudioDeviceType',
  full_name='rv.data.VideoInput.AudioDeviceType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AUDIO_DEVICE_TYPE_DEFAULT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUDIO_DEVICE_TYPE_NONE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUDIO_DEVICE_TYPE_ALTERNATE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=505,
  serialized_end=614,
)
_sym_db.RegisterEnumDescriptor(_VIDEOINPUT_AUDIODEVICETYPE)


_VIDEOINPUT_SETTINGSDOCUMENT = _descriptor.Descriptor(
  name='SettingsDocument',
  full_name='rv.data.VideoInput.SettingsDocument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputs', full_name='rv.data.VideoInput.SettingsDocument.inputs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=503,
)

_VIDEOINPUT = _descriptor.Descriptor(
  name='VideoInput',
  full_name='rv.data.VideoInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='rv.data.VideoInput.uuid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_description', full_name='rv.data.VideoInput.user_description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='video_input_device', full_name='rv.data.VideoInput.video_input_device', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='display_color', full_name='rv.data.VideoInput.display_color', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='thumbnail_path', full_name='rv.data.VideoInput.thumbnail_path', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='audio_type', full_name='rv.data.VideoInput.audio_type', index=5,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='audio_device', full_name='rv.data.VideoInput.audio_device', index=6,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='video_device', full_name='rv.data.VideoInput.video_device', index=7,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_VIDEOINPUT_SETTINGSDOCUMENT, ],
  enum_types=[
    _VIDEOINPUT_AUDIODEVICETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='AltAudioSource', full_name='rv.data.VideoInput.AltAudioSource',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=83,
  serialized_end=632,
)


_AUDIOINPUT_BEHAVIORMODE_ON = _descriptor.Descriptor(
  name='On',
  full_name='rv.data.AudioInput.BehaviorMode.On',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1110,
  serialized_end=1114,
)

_AUDIOINPUT_BEHAVIORMODE_OFF = _descriptor.Descriptor(
  name='Off',
  full_name='rv.data.AudioInput.BehaviorMode.Off',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1116,
  serialized_end=1121,
)

_AUDIOINPUT_BEHAVIORMODE_AUTOOFF = _descriptor.Descriptor(
  name='AutoOff',
  full_name='rv.data.AudioInput.BehaviorMode.AutoOff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1123,
  serialized_end=1132,
)

_AUDIOINPUT_BEHAVIORMODE_AUTOON = _descriptor.Descriptor(
  name='AutoOn',
  full_name='rv.data.AudioInput.BehaviorMode.AutoOn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='linked_video_inputs', full_name='rv.data.AudioInput.BehaviorMode.AutoOn.linked_video_inputs', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1134,
  serialized_end=1171,
)

_AUDIOINPUT_BEHAVIORMODE = _descriptor.Descriptor(
  name='BehaviorMode',
  full_name='rv.data.AudioInput.BehaviorMode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='on', full_name='rv.data.AudioInput.BehaviorMode.on', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='off', full_name='rv.data.AudioInput.BehaviorMode.off', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='auto_on', full_name='rv.data.AudioInput.BehaviorMode.auto_on', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='auto_off', full_name='rv.data.AudioInput.BehaviorMode.auto_off', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_AUDIOINPUT_BEHAVIORMODE_ON, _AUDIOINPUT_BEHAVIORMODE_OFF, _AUDIOINPUT_BEHAVIORMODE_AUTOOFF, _AUDIOINPUT_BEHAVIORMODE_AUTOON, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Mode', full_name='rv.data.AudioInput.BehaviorMode.Mode',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=868,
  serialized_end=1179,
)

_AUDIOINPUT = _descriptor.Descriptor(
  name='AudioInput',
  full_name='rv.data.AudioInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='rv.data.AudioInput.uuid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_description', full_name='rv.data.AudioInput.user_description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='behavior_mode', full_name='rv.data.AudioInput.behavior_mode', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='audio_device', full_name='rv.data.AudioInput.audio_device', index=3,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='video_device', full_name='rv.data.AudioInput.video_device', index=4,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_AUDIOINPUT_BEHAVIORMODE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Source', full_name='rv.data.AudioInput.Source',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=635,
  serialized_end=1189,
)

_VIDEOINPUT_SETTINGSDOCUMENT.fields_by_name['inputs'].message_type = _VIDEOINPUT
_VIDEOINPUT_SETTINGSDOCUMENT.containing_type = _VIDEOINPUT
_VIDEOINPUT.fields_by_name['uuid'].message_type = basicTypes__pb2._UUID
_VIDEOINPUT.fields_by_name['video_input_device'].message_type = graphicsData__pb2._MEDIA_VIDEODEVICE
_VIDEOINPUT.fields_by_name['display_color'].message_type = basicTypes__pb2._COLOR
_VIDEOINPUT.fields_by_name['thumbnail_path'].message_type = basicTypes__pb2._URL
_VIDEOINPUT.fields_by_name['audio_type'].enum_type = _VIDEOINPUT_AUDIODEVICETYPE
_VIDEOINPUT.fields_by_name['audio_device'].message_type = digitalAudio__pb2._DIGITALAUDIO_DEVICE
_VIDEOINPUT.fields_by_name['video_device'].message_type = graphicsData__pb2._MEDIA_VIDEODEVICE
_VIDEOINPUT_AUDIODEVICETYPE.containing_type = _VIDEOINPUT
_VIDEOINPUT.oneofs_by_name['AltAudioSource'].fields.append(
  _VIDEOINPUT.fields_by_name['audio_device'])
_VIDEOINPUT.fields_by_name['audio_device'].containing_oneof = _VIDEOINPUT.oneofs_by_name['AltAudioSource']
_VIDEOINPUT.oneofs_by_name['AltAudioSource'].fields.append(
  _VIDEOINPUT.fields_by_name['video_device'])
_VIDEOINPUT.fields_by_name['video_device'].containing_oneof = _VIDEOINPUT.oneofs_by_name['AltAudioSource']
_AUDIOINPUT_BEHAVIORMODE_ON.containing_type = _AUDIOINPUT_BEHAVIORMODE
_AUDIOINPUT_BEHAVIORMODE_OFF.containing_type = _AUDIOINPUT_BEHAVIORMODE
_AUDIOINPUT_BEHAVIORMODE_AUTOOFF.containing_type = _AUDIOINPUT_BEHAVIORMODE
_AUDIOINPUT_BEHAVIORMODE_AUTOON.containing_type = _AUDIOINPUT_BEHAVIORMODE
_AUDIOINPUT_BEHAVIORMODE.fields_by_name['on'].message_type = _AUDIOINPUT_BEHAVIORMODE_ON
_AUDIOINPUT_BEHAVIORMODE.fields_by_name['off'].message_type = _AUDIOINPUT_BEHAVIORMODE_OFF
_AUDIOINPUT_BEHAVIORMODE.fields_by_name['auto_on'].message_type = _AUDIOINPUT_BEHAVIORMODE_AUTOON
_AUDIOINPUT_BEHAVIORMODE.fields_by_name['auto_off'].message_type = _AUDIOINPUT_BEHAVIORMODE_AUTOOFF
_AUDIOINPUT_BEHAVIORMODE.containing_type = _AUDIOINPUT
_AUDIOINPUT_BEHAVIORMODE.oneofs_by_name['Mode'].fields.append(
  _AUDIOINPUT_BEHAVIORMODE.fields_by_name['on'])
_AUDIOINPUT_BEHAVIORMODE.fields_by_name['on'].containing_oneof = _AUDIOINPUT_BEHAVIORMODE.oneofs_by_name['Mode']
_AUDIOINPUT_BEHAVIORMODE.oneofs_by_name['Mode'].fields.append(
  _AUDIOINPUT_BEHAVIORMODE.fields_by_name['off'])
_AUDIOINPUT_BEHAVIORMODE.fields_by_name['off'].containing_oneof = _AUDIOINPUT_BEHAVIORMODE.oneofs_by_name['Mode']
_AUDIOINPUT_BEHAVIORMODE.oneofs_by_name['Mode'].fields.append(
  _AUDIOINPUT_BEHAVIORMODE.fields_by_name['auto_on'])
_AUDIOINPUT_BEHAVIORMODE.fields_by_name['auto_on'].containing_oneof = _AUDIOINPUT_BEHAVIORMODE.oneofs_by_name['Mode']
_AUDIOINPUT_BEHAVIORMODE.oneofs_by_name['Mode'].fields.append(
  _AUDIOINPUT_BEHAVIORMODE.fields_by_name['auto_off'])
_AUDIOINPUT_BEHAVIORMODE.fields_by_name['auto_off'].containing_oneof = _AUDIOINPUT_BEHAVIORMODE.oneofs_by_name['Mode']
_AUDIOINPUT.fields_by_name['uuid'].message_type = basicTypes__pb2._UUID
_AUDIOINPUT.fields_by_name['behavior_mode'].message_type = _AUDIOINPUT_BEHAVIORMODE
_AUDIOINPUT.fields_by_name['audio_device'].message_type = digitalAudio__pb2._DIGITALAUDIO_DEVICE
_AUDIOINPUT.fields_by_name['video_device'].message_type = graphicsData__pb2._MEDIA_VIDEODEVICE
_AUDIOINPUT.oneofs_by_name['Source'].fields.append(
  _AUDIOINPUT.fields_by_name['audio_device'])
_AUDIOINPUT.fields_by_name['audio_device'].containing_oneof = _AUDIOINPUT.oneofs_by_name['Source']
_AUDIOINPUT.oneofs_by_name['Source'].fields.append(
  _AUDIOINPUT.fields_by_name['video_device'])
_AUDIOINPUT.fields_by_name['video_device'].containing_oneof = _AUDIOINPUT.oneofs_by_name['Source']
DESCRIPTOR.message_types_by_name['VideoInput'] = _VIDEOINPUT
DESCRIPTOR.message_types_by_name['AudioInput'] = _AUDIOINPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoInput = _reflection.GeneratedProtocolMessageType('VideoInput', (_message.Message,), {

  'SettingsDocument' : _reflection.GeneratedProtocolMessageType('SettingsDocument', (_message.Message,), {
    'DESCRIPTOR' : _VIDEOINPUT_SETTINGSDOCUMENT,
    '__module__' : 'input_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.VideoInput.SettingsDocument)
    })
  ,
  'DESCRIPTOR' : _VIDEOINPUT,
  '__module__' : 'input_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.VideoInput)
  })
_sym_db.RegisterMessage(VideoInput)
_sym_db.RegisterMessage(VideoInput.SettingsDocument)

AudioInput = _reflection.GeneratedProtocolMessageType('AudioInput', (_message.Message,), {

  'BehaviorMode' : _reflection.GeneratedProtocolMessageType('BehaviorMode', (_message.Message,), {

    'On' : _reflection.GeneratedProtocolMessageType('On', (_message.Message,), {
      'DESCRIPTOR' : _AUDIOINPUT_BEHAVIORMODE_ON,
      '__module__' : 'input_pb2'
      # @@protoc_insertion_point(class_scope:rv.data.AudioInput.BehaviorMode.On)
      })
    ,

    'Off' : _reflection.GeneratedProtocolMessageType('Off', (_message.Message,), {
      'DESCRIPTOR' : _AUDIOINPUT_BEHAVIORMODE_OFF,
      '__module__' : 'input_pb2'
      # @@protoc_insertion_point(class_scope:rv.data.AudioInput.BehaviorMode.Off)
      })
    ,

    'AutoOff' : _reflection.GeneratedProtocolMessageType('AutoOff', (_message.Message,), {
      'DESCRIPTOR' : _AUDIOINPUT_BEHAVIORMODE_AUTOOFF,
      '__module__' : 'input_pb2'
      # @@protoc_insertion_point(class_scope:rv.data.AudioInput.BehaviorMode.AutoOff)
      })
    ,

    'AutoOn' : _reflection.GeneratedProtocolMessageType('AutoOn', (_message.Message,), {
      'DESCRIPTOR' : _AUDIOINPUT_BEHAVIORMODE_AUTOON,
      '__module__' : 'input_pb2'
      # @@protoc_insertion_point(class_scope:rv.data.AudioInput.BehaviorMode.AutoOn)
      })
    ,
    'DESCRIPTOR' : _AUDIOINPUT_BEHAVIORMODE,
    '__module__' : 'input_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.AudioInput.BehaviorMode)
    })
  ,
  'DESCRIPTOR' : _AUDIOINPUT,
  '__module__' : 'input_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.AudioInput)
  })
_sym_db.RegisterMessage(AudioInput)
_sym_db.RegisterMessage(AudioInput.BehaviorMode)
_sym_db.RegisterMessage(AudioInput.BehaviorMode.On)
_sym_db.RegisterMessage(AudioInput.BehaviorMode.Off)
_sym_db.RegisterMessage(AudioInput.BehaviorMode.AutoOff)
_sym_db.RegisterMessage(AudioInput.BehaviorMode.AutoOn)


# @@protoc_insertion_point(module_scope)
