# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: propSlide.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import slide_pb2 as slide__pb2
import effects_pb2 as effects__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='propSlide.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fpropSlide.proto\x12\x07rv.data\x1a\x0bslide.proto\x1a\reffects.proto\"X\n\tPropSlide\x12\"\n\nbase_slide\x18\x01 \x01(\x0b\x32\x0e.rv.data.Slide\x12\'\n\ntransition\x18\x02 \x01(\x0b\x32\x13.rv.data.Transitionb\x06proto3'
  ,
  dependencies=[slide__pb2.DESCRIPTOR,effects__pb2.DESCRIPTOR,])




_PROPSLIDE = _descriptor.Descriptor(
  name='PropSlide',
  full_name='rv.data.PropSlide',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_slide', full_name='rv.data.PropSlide.base_slide', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transition', full_name='rv.data.PropSlide.transition', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=144,
)

_PROPSLIDE.fields_by_name['base_slide'].message_type = slide__pb2._SLIDE
_PROPSLIDE.fields_by_name['transition'].message_type = effects__pb2._TRANSITION
DESCRIPTOR.message_types_by_name['PropSlide'] = _PROPSLIDE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PropSlide = _reflection.GeneratedProtocolMessageType('PropSlide', (_message.Message,), {
  'DESCRIPTOR' : _PROPSLIDE,
  '__module__' : 'propSlide_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.PropSlide)
  })
_sym_db.RegisterMessage(PropSlide)


# @@protoc_insertion_point(module_scope)
