# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2
import slide_pb2 as slide__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='stage.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bstage.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\x1a\x0bslide.proto\"\xb7\x02\n\x05Stage\x1aR\n\x06Layout\x12\x1b\n\x04uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1d\n\x05slide\x18\x03 \x01(\x0b\x32\x0e.rv.data.Slide\x1a\x66\n\x08\x44ocument\x12\x32\n\x10\x61pplication_info\x18\x01 \x01(\x0b\x32\x18.rv.data.ApplicationInfo\x12&\n\x07layouts\x18\x02 \x03(\x0b\x32\x15.rv.data.Stage.Layout\x1ar\n\x10ScreenAssignment\x12.\n\x06screen\x18\x01 \x01(\x0b\x32\x1e.rv.data.CollectionElementType\x12.\n\x06layout\x18\x02 \x01(\x0b\x32\x1e.rv.data.CollectionElementTypeb\x06proto3'
  ,
  dependencies=[basicTypes__pb2.DESCRIPTOR,slide__pb2.DESCRIPTOR,])




_STAGE_LAYOUT = _descriptor.Descriptor(
  name='Layout',
  full_name='rv.data.Stage.Layout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='rv.data.Stage.Layout.uuid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='rv.data.Stage.Layout.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='slide', full_name='rv.data.Stage.Layout.slide', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=147,
)

_STAGE_DOCUMENT = _descriptor.Descriptor(
  name='Document',
  full_name='rv.data.Stage.Document',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='application_info', full_name='rv.data.Stage.Document.application_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='layouts', full_name='rv.data.Stage.Document.layouts', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=251,
)

_STAGE_SCREENASSIGNMENT = _descriptor.Descriptor(
  name='ScreenAssignment',
  full_name='rv.data.Stage.ScreenAssignment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='screen', full_name='rv.data.Stage.ScreenAssignment.screen', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='layout', full_name='rv.data.Stage.ScreenAssignment.layout', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=367,
)

_STAGE = _descriptor.Descriptor(
  name='Stage',
  full_name='rv.data.Stage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_STAGE_LAYOUT, _STAGE_DOCUMENT, _STAGE_SCREENASSIGNMENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=367,
)

_STAGE_LAYOUT.fields_by_name['uuid'].message_type = basicTypes__pb2._UUID
_STAGE_LAYOUT.fields_by_name['slide'].message_type = slide__pb2._SLIDE
_STAGE_LAYOUT.containing_type = _STAGE
_STAGE_DOCUMENT.fields_by_name['application_info'].message_type = basicTypes__pb2._APPLICATIONINFO
_STAGE_DOCUMENT.fields_by_name['layouts'].message_type = _STAGE_LAYOUT
_STAGE_DOCUMENT.containing_type = _STAGE
_STAGE_SCREENASSIGNMENT.fields_by_name['screen'].message_type = basicTypes__pb2._COLLECTIONELEMENTTYPE
_STAGE_SCREENASSIGNMENT.fields_by_name['layout'].message_type = basicTypes__pb2._COLLECTIONELEMENTTYPE
_STAGE_SCREENASSIGNMENT.containing_type = _STAGE
DESCRIPTOR.message_types_by_name['Stage'] = _STAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Stage = _reflection.GeneratedProtocolMessageType('Stage', (_message.Message,), {

  'Layout' : _reflection.GeneratedProtocolMessageType('Layout', (_message.Message,), {
    'DESCRIPTOR' : _STAGE_LAYOUT,
    '__module__' : 'stage_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.Stage.Layout)
    })
  ,

  'Document' : _reflection.GeneratedProtocolMessageType('Document', (_message.Message,), {
    'DESCRIPTOR' : _STAGE_DOCUMENT,
    '__module__' : 'stage_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.Stage.Document)
    })
  ,

  'ScreenAssignment' : _reflection.GeneratedProtocolMessageType('ScreenAssignment', (_message.Message,), {
    'DESCRIPTOR' : _STAGE_SCREENASSIGNMENT,
    '__module__' : 'stage_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.Stage.ScreenAssignment)
    })
  ,
  'DESCRIPTOR' : _STAGE,
  '__module__' : 'stage_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.Stage)
  })
_sym_db.RegisterMessage(Stage)
_sym_db.RegisterMessage(Stage.Layout)
_sym_db.RegisterMessage(Stage.Document)
_sym_db.RegisterMessage(Stage.ScreenAssignment)


# @@protoc_insertion_point(module_scope)
