# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: template.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2
import slide_pb2 as slide__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='template.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0etemplate.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\x1a\x0bslide.proto\"\xb8\x02\n\x08Template\x1a\x39\n\x05Slide\x12\"\n\nbase_slide\x18\x01 \x01(\x0b\x32\x0e.rv.data.Slide\x12\x0c\n\x04name\x18\x02 \x01(\t\x1ag\n\x08\x44ocument\x12\x32\n\x10\x61pplication_info\x18\x01 \x01(\x0b\x32\x18.rv.data.ApplicationInfo\x12\'\n\x06slides\x18\x03 \x03(\x0b\x32\x17.rv.data.Template.Slide\x1a\x87\x01\n\x0eIdentification\x12\x1b\n\x04uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12\x0c\n\x04name\x18\x02 \x01(\t\x12!\n\nslide_uuid\x18\x03 \x01(\x0b\x32\r.rv.data.UUID\x12\x12\n\nslide_name\x18\x04 \x01(\t\x12\x13\n\x0bslide_index\x18\x05 \x01(\rb\x06proto3'
  ,
  dependencies=[basicTypes__pb2.DESCRIPTOR,slide__pb2.DESCRIPTOR,])




_TEMPLATE_SLIDE = _descriptor.Descriptor(
  name='Slide',
  full_name='rv.data.Template.Slide',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_slide', full_name='rv.data.Template.Slide.base_slide', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='rv.data.Template.Slide.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=128,
)

_TEMPLATE_DOCUMENT = _descriptor.Descriptor(
  name='Document',
  full_name='rv.data.Template.Document',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='application_info', full_name='rv.data.Template.Document.application_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='slides', full_name='rv.data.Template.Document.slides', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=233,
)

_TEMPLATE_IDENTIFICATION = _descriptor.Descriptor(
  name='Identification',
  full_name='rv.data.Template.Identification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='rv.data.Template.Identification.uuid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='rv.data.Template.Identification.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='slide_uuid', full_name='rv.data.Template.Identification.slide_uuid', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='slide_name', full_name='rv.data.Template.Identification.slide_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='slide_index', full_name='rv.data.Template.Identification.slide_index', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=371,
)

_TEMPLATE = _descriptor.Descriptor(
  name='Template',
  full_name='rv.data.Template',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_TEMPLATE_SLIDE, _TEMPLATE_DOCUMENT, _TEMPLATE_IDENTIFICATION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=371,
)

_TEMPLATE_SLIDE.fields_by_name['base_slide'].message_type = slide__pb2._SLIDE
_TEMPLATE_SLIDE.containing_type = _TEMPLATE
_TEMPLATE_DOCUMENT.fields_by_name['application_info'].message_type = basicTypes__pb2._APPLICATIONINFO
_TEMPLATE_DOCUMENT.fields_by_name['slides'].message_type = _TEMPLATE_SLIDE
_TEMPLATE_DOCUMENT.containing_type = _TEMPLATE
_TEMPLATE_IDENTIFICATION.fields_by_name['uuid'].message_type = basicTypes__pb2._UUID
_TEMPLATE_IDENTIFICATION.fields_by_name['slide_uuid'].message_type = basicTypes__pb2._UUID
_TEMPLATE_IDENTIFICATION.containing_type = _TEMPLATE
DESCRIPTOR.message_types_by_name['Template'] = _TEMPLATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Template = _reflection.GeneratedProtocolMessageType('Template', (_message.Message,), {

  'Slide' : _reflection.GeneratedProtocolMessageType('Slide', (_message.Message,), {
    'DESCRIPTOR' : _TEMPLATE_SLIDE,
    '__module__' : 'template_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.Template.Slide)
    })
  ,

  'Document' : _reflection.GeneratedProtocolMessageType('Document', (_message.Message,), {
    'DESCRIPTOR' : _TEMPLATE_DOCUMENT,
    '__module__' : 'template_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.Template.Document)
    })
  ,

  'Identification' : _reflection.GeneratedProtocolMessageType('Identification', (_message.Message,), {
    'DESCRIPTOR' : _TEMPLATE_IDENTIFICATION,
    '__module__' : 'template_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.Template.Identification)
    })
  ,
  'DESCRIPTOR' : _TEMPLATE,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.Template)
  })
_sym_db.RegisterMessage(Template)
_sym_db.RegisterMessage(Template.Slide)
_sym_db.RegisterMessage(Template.Document)
_sym_db.RegisterMessage(Template.Identification)


# @@protoc_insertion_point(module_scope)
